// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bljybyvmmyczoavsixdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsanlieXZtbXljem9hdnNpeGRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5MDI4OTAsImV4cCI6MjA0OTQ3ODg5MH0.qqEudgkdA_jcURMN0JK39U_HsYnd3HC2vo6JyUFdQkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);